language: haskell

before_install:
  - git clone https://github.com/guillaume-nargeot/hpc-coveralls
  - cd hpc-coveralls
  - cabal install
  - cd ..

script:
  - cabal configure --enable-tests --enable-library-coverage
  - cabal build
  - run-cabal-test --show-details=always

after_script:
  - hpc-coveralls test-all
