language: haskell

ghc:
  - 7.10

before_install:
  - cabal install --dependencies-only --enable-tests

script:
  - cabal configure --enable-tests --enable-coverage -v2
  - cabal build
  - cabal test

after_script:
  - git clone -b master https://github.com/guillaume-nargeot/hpc-coveralls
  - cd hpc-coveralls
  - cabal install
  - cd ..
  - hpc-coveralls test-zero --exclude-dir=test0 --display-report --dont-send
  - hpc-coveralls test-one --exclude-dir=test1 --display-report --dont-send
  - hpc-coveralls test-two --exclude-dir=test2 --display-report --dont-send
  - hpc-coveralls test-three --exclude-dir=test3 --display-report --dont-send
  - hpc-coveralls test-zero test-one test-two test-three --exclude-dir=test0 --exclude-dir=test1 --exclude-dir=test2 --exclude-dir=test3
