env:
  - GHCVER=7.10.1

before_install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-1.22 ghc-$GHCVER happy-1.19.4 alex-3.1.3
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/alex/3.1.3/bin:/opt/happy/1.19.4/bin:$PATH

install:
  - cabal-1.22 update
  - cabal-1.22 configure --enable-tests --enable-coverage -v2

script:
  - cabal-1.22 build
  - cabal-1.22 test --show-details=streaming

after_script:
  - cabal-1.22 install hpc-coveralls
  - hpc-coveralls/dist/build/hpc-coveralls/hpc-coveralls --exclude-dir=test --display-report test-all
