language: haskell

ghc:
  - 7.6.3
  - 7.8.3

before_install:
  - cabal install hpc-coveralls-0.8.1

script:
  - cabal configure --enable-tests --enable-library-coverage -v2
  - cabal build
  - run-cabal-test --cabal-name=cabal --show-details=always

after_script:
  - hpc-coveralls test-one --exclude-dir=test1 --display-report --dont-send
  - hpc-coveralls test-two --exclude-dir=test2 --display-report --dont-send
  - hpc-coveralls test-three --exclude-dir=test3 --display-report --dont-send
  - hpc-coveralls test-one test-two test-three --exclude-dir=test1 --exclude-dir=test2 --exclude-dir=test3
