language: haskell

ghc:
  - 7.6.3
  - 7.8.3

before_install:
  - git clone -b fix-otherwise-coverage https://github.com/guillaume-nargeot/hpc-coveralls
  - cd hpc-coveralls
  - cabal install
  - cd ..

script:
  - cabal configure --enable-tests --enable-library-coverage -v2
  - cabal build
  - run-cabal-test --cabal-name=cabal --show-details=always

after_script:
  - hpc-coveralls test-one --exclude-dir=test1 --display-report --dont-send
  - hpc-coveralls test-two --exclude-dir=test2 --display-report --dont-send
  - hpc-coveralls test-three --exclude-dir=test3 --display-report --dont-send
