language: haskell

ghc:
  - 7.8

before_install:
  - git clone -b dump-directories-on-failure https://github.com/guillaume-nargeot/hpc-coveralls
  - cd hpc-coveralls
  - cabal install
  - cd ..

script:
  - cabal configure --enable-tests --enable-library-coverage -v2
  - cabal build
  - cabal test --show-details=always

after_script:
  - mv dist/hpc dist/hpc2
  - hpc-coveralls test-one test-two --exclude-dir=test1 --exclude-dir=test2 --dont-send
  - mv dist/hpc2 dist/hpc
  - mv dist/hpc/tix dist/hpc/tix2
  - hpc-coveralls test-one test-two --exclude-dir=test1 --exclude-dir=test2 --dont-send
  - mv dist/hpc/tix2 dist/hpc/tix
  - hpc-coveralls test-one test-two --exclude-dir=test1 --exclude-dir=test2 --dont-send
