language: haskell

ghc:
  - 7.4
  - 7.6
  - 7.8

script:
  - |
    if [[ $GHCVER = 7.8* ]]; then
        cabal configure --enable-tests --enable-library-coverage -v2
    else
        cabal configure --enable-tests -v2
    fi
  - cabal build && cabal test

after_script:
  - env
  - |
    if [[ $GHCVER = 7.8* ]]; then
      cabal install hpc-coveralls
      hpc-coveralls test-one test-two --exclude-dir=test1 --exclude-dir=test2
    fi
