language: haskell

ghc:
  - 7.4
  - 7.6
  - 7.8

script:
  - |
    if [[ `ghc --version` = *7.8.? ]]; then
        cabal configure --enable-tests --enable-library-coverage -v2
    else
        cabal configure --enable-tests -v2
    fi
  - cabal build && cabal test

after_script:
  - |
    if [[ `ghc --version` = *7.8.? ]]; then
      cabal install hpc-coveralls
      hpc-coveralls test-one --exclude-dir=test1
    fi
