env:
  - GHCVER=7.4.2
  - GHCVER=7.6.3
  - GHCVER=7.8.1

matrix:
  allow_failures:
    - env: GHCVER=7.8.1

before_install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-1.18 ghc-$GHCVER happy
  - export PATH=/opt/ghc/$GHCVER/bin:$PATH

install:
  - cabal-1.18 update
  - cabal-1.18 configure --enable-tests --enable-library-coverage -v2
  - git clone https://github.com/guillaume-nargeot/hpc-coveralls
  - cd hpc-coveralls
  - cabal-1.18 install --avoid-reinstalls
  - cd ..

script:
  - cabal-1.18 build
  - |
    if [ $GHCVER = "7.8.1" ]; then
      cabal-1.18 test --show-details=always
    else
      hpc-coveralls/dist/build/run-cabal-test/run-cabal-test --cabal-name=cabal-1.18 --show-details=always
    fi

after_script:
  - hpc-coveralls/dist/build/hpc-coveralls/hpc-coveralls --exclude-dir=test --display-report test-all
