language: haskell

ghc:
  - 7.6
  - 7.8

before_install:
  - git clone -b print-coveralls-response https://github.com/guillaume-nargeot/hpc-coveralls
  - cd hpc-coveralls
  - cabal install
  - cd ..
#  - cabal install hpc-coveralls

script:
  - cabal configure --enable-tests --enable-library-coverage
  - cabal build
  - run-cabal-test --cabal-name=cabal --show-details=always

after_script:
  - hpc-coveralls test-one test-two --exclude-dir=test1 --exclude-dir=test2 --coverage-mode=AllowPartialLines --display-report --dont-send
  - hpc-coveralls test-one test-two --exclude-dir=test1 --exclude-dir=test2 --coverage-mode=StrictlyFullLines --display-report --dont-send
  - hpc-coveralls test-one test-two --exclude-dir=test1 --exclude-dir=test2 --display-report --dont-send
  - hpc-coveralls test-one test-two --exclude-dir=test1 --exclude-dir=test2 --print-response
