env:
  - CABALVER=1.22 GHCVER=7.8.3
  - CABALVER=1.22 GHCVER=7.10.1

before_install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER happy
  - export PATH=/opt/ghc/$GHCVER/bin:$PATH

install:
  - cabal-$CABALVER update
  - travis_retry sudo apt-get -q -y install hlint || cabal-$CABALVER install hlint
  - cabal-$CABALVER install --only-dependencies --enable-tests --enable-benchmarks

script:
  - cabal-$CABALVER configure --enable-tests --enable-benchmarks --enable-coverage -v2
  - cabal-$CABALVER build
  - cabal-$CABALVER test --show-details=always

after_script:
  - git clone -b read-cabal-file https://github.com/guillaume-nargeot/hpc-coveralls
  - cd hpc-coveralls
  - cabal install
  - cd ..
  - hpc-coveralls/dist/build/hpc-coveralls/hpc-coveralls test-all --exclude-dir=test --display-report
