language: haskell

ghc: 7.8

script:
  - cabal configure --enable-tests --enable-library-coverage && cabal build && cabal test --show-details=always

after_script:
  - cabal install hpc-coveralls
  - hpc-coveralls test-one --exclude-dir=test1
